version: '2.4'

services:
  portainer:
    container_name: portainer-edge-agent
    build: ./
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - /:/host
      - portainer_agent_data:/data
    environment:
      - EDGE=1
      - EDGE_ID=$EDGE_ID
      - EDGE_INSECURE_POLL=1
      - EDGE_KEY=$EDGE_KEY
      - CAP_HOST_MANAGEMENT=1
    ports:
      - '0.0.0.0:8000:8000'

volumes:
  portainer_agent_data:
